apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-routes
spec:
  parentRefs:
    - name: gittex-gateway
  hostnames:
    - ticketing.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/users
      backendRefs:
        - name: auth-srv
          port: 3000
    - matches:
        - path:
            type: PathPrefix
            value: /api/tickets
      backendRefs:
        - name: tickets-srv
          port: 3000
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: client-src
          port: 3000
